version: 2
sources:
  - name: bronze_hr
    schema: bronze # ou o schema onde o Hop salvou
    tables:
      - name: stg_base_icms
        columns:
          - name: id_chave
            description: "Chave primária que identifica a transação."
            tests:
              - unique
              - not_null
