services:
  dbt:
    image: ghcr.io/dbt-labs/dbt-postgres:latest
    entrypoint: "" # <--- ADICIONE ESTA LINHA (limpa o comando padrão)
    command: tail -f /dev/null # Mantém o container vivo
    volumes:
      - .:/usr/app # Mapeia a pasta local para o contêiner
    ports:
      - "8082:8080"
    tty: true
    stdin_open: true
    working_dir: /usr/app
    environment:
      - DBT_PROFILE_DIR=/usr/app # Onde está o seu profiles.yml
    networks:
      - dados_dbt

volumes:
  pgdata:

networks:
  dados_dbt:
    external: true